### ISSUE TITLE
Add description to welcome screen

### ISSUE THREAD

**Issue by janrudolph** [assistify/outlook-plugin#17]
If the user opens the Assistify Outlook plugin for the first time, the user just sees an input for the server URL. At this point we need some explanation about the plugin, like "Welcome to the Assistify Outlook Plugin. With this plugin you are able to shift emails to Assistify in order to discuss emails with your colleagues. At first, please add your server information."

**Comment by janrudolph** [comment]
@ThomasRoehl Do we have a PR for this?

**Comment by janrudolph** [comment]
**Heading:** 
Assistify Outlook Plugin

**Text:** 
Diskutiere ganz einfach E-Mails mit deinen Kollegen direkt in Assistify! 
Melde dich dazu bitte zunächst an.

**Comment by vickyokrm** [comment]
PR #33
