### ISSUE TITLE
Success handling (notification/navigation)

### ISSUE THREAD

**Issue by mrsimpson** [assistify/outlook-plugin#31]
Once a discussion has been successfully created, a success message (e. g. a toast) shall be displayed

Ideally, a navigation to the target channel should be executed

**Comment by janrudolph** [comment]
Let's add a success page after forwarding the mail. 

## Mockup

![image](https://user-images.githubusercontent.com/3596824/63749165-28253280-c8ab-11e9-9bf2-829924b50a00.png)
Great! Your discussion has been successfully created!

You like to add a comment? - (LINK TO DISCUSSION)[Jump to your discussion]!



## Notes

- No automatic redirect to Assistify. The user has to click on the link.
- Do not forget German translation ;-)

---
sample success icon: https://www.flaticon.com/free-icon/success_148767

**Comment by ruKurz** [comment]
make sure, the analytics call is not blocking the success info
