### ISSUE TITLE
Comfortable selection of parent channel

### ISSUE THREAD

**Issue by mrsimpson** [assistify/outlook-plugin#32]
Once a user is joined in multiple channels, the selection list can become very long.

## Options

- Input for a search term
- List recently used channels first

**Comment by vickyokrm** [comment]
@janrudolph Do we need Room Search feature to implement or shall we close this issue?

**Comment by janrudolph** [comment]
The current state is fine. We do not need a search right now. However we should open an issue for that as a reminder.
